version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: UserPass@1234
      MYSQL_DATABASE: ma_base
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts:/var/lib/mysql-files

volumes:
  mysql-data: